- name: Install additional packages on the node
  yum:
    name:
      - "wget"
      - "git"
      - "net-tools"
      - "bind-utils"
      - "iptables-services"
      - "bridge-utils"
      - "docker"
    state: "present"
  become: true

- name: Add current user to root group
  shell: usermod -aG root `whoami`
  become: true

- name: Update docker config
  shell: echo "INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'" >> /etc/sysconfig/docker
  become: true
   
- name: Restart Docker
  shell: systemctl start docker && systemctl enable docker && systemctl start docker
  become: true